# Generated by Django 3.1.2 on 2020-10-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app_dev', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetoken',
            name='store_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
