# Generated by Django 3.1.2 on 2020-10-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app_dev', '0002_auto_20201025_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='image',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
