# Generated by Django 3.1.2 on 2020-10-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app_dev', '0002_storetoken_store_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shopify_app_dev.order'),
            preserve_default=False,
        ),
    ]
