# Generated by Django 3.1.2 on 2020-10-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app_dev', '0003_auto_20201025_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopify_app_dev.product'),
            preserve_default=False,
        ),
    ]
