# Generated by Django 3.1.2 on 2020-10-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app_dev', '0004_productvariant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='weight_unit',
            field=models.CharField(default='', max_length=10),
        ),
    ]
