# Generated by Django 3.1.2 on 2020-10-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app_dev', '0005_auto_20201025_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
