# Generated by Django 3.1.2 on 2020-10-25 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_app_dev', '0007_remove_abandoncartlineitem_variant_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdiscountcode',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='orderdiscountcode',
            name='discount_type',
        ),
    ]
